CREATE DATABASE CITYARTFACTORY;

USE CITYARTFACTORY;

CREATE TABLE CAT_IMAGE(
   IMAGE_ID INT NOT NULL AUTO_INCREMENT,
   IMAGE_TYPE VARCHAR(100) NOT NULL,
   FILENAME VARCHAR(255),
   PRIMARY KEY pk_image_id( IMAGE_ID )
);

CREATE TABLE CAT_USER(
   USER_ID INT NOT NULL AUTO_INCREMENT,
   CATEGORY VARCHAR(100) NOT NULL,
   NAME_USER VARCHAR(200),
   EMAIL VARCHAR(100),
   PHONENO VARCHAR(100),
   ADDRESS TEXT,
   OFFER_IND char(1),
   IMAGE_ID INT,
   FOREIGN KEY fk_image_id (IMAGE_ID)
	REFERENCES CAT_IMAGE(IMAGE_ID),
   PRIMARY KEY pk_user_id( USER_ID )
);
